version: "3.9"

services:
  secondary-api:
    build: .
    container_name: secondary-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000 --reload
